org.gradle.caching=true
group=io.ballerina.lib
version=1.0.1-SNAPSHOT

checkstylePluginVersion=10.12.0
spotbugsPluginVersion=6.0.18
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.5.0
releasePluginVersion=2.8.1
ballerinaGradlePluginVersion=2.3.0

ballerinaLangVersion=2201.12.0

commonsCompressVersion=1.27.1
commonsIoVersion=2.18.0
