[package]
distribution = "2201.12.0"
org = "ballerina"
name = "zip"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Area/Storage & File Management", "Type/Library"]
repository = "https://github.com/ballerina-platform/module-ballerina-zip"
icon = "icon.png"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib.zip"
artifactId = "zip-native"
version = "@toml.version@"
path = "../native/build/libs/zip-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "@commons.compress.version@"
path = "./lib/commons-compress-@commons.compress.version@.jar"

[[platform.java21.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "@commons.io.version@"
path = "./lib/commons-io-@commons.io.version@.jar"
