[package]
distribution = "2201.12.0"
org = "ballerina"
name = "zip"
version = "1.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Area/Storage & File Management", "Type/Library"]
repository = "https://github.com/ballerina-platform/module-ballerina-zip"
icon = "icon.png"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib.zip"
artifactId = "zip-native"
version = "1.0.1"
path = "../native/build/libs/zip-native-1.0.1.jar"

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.27.1"
path = "./lib/commons-compress-1.27.1.jar"

[[platform.java21.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.18.0"
path = "./lib/commons-io-2.18.0.jar"
